=== AyaSHEHAT/Attendance_Project/XML files/Data.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:simpleType name="status">
		<xs:restriction base="xs:string">
		<xs:enumeration value="absent" />
		<xs:enumeration value="present"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:element name="Data">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="Users">
			<xs:complexType>
				<xs:sequence>
					<xs:element name="user" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						<xs:element name="id" type="xs:integer"/>
						<xs:element name="name" type="xs:string"/>
						<xs:element name="email" type="xs:string"/>
						<xs:element name="address" type="xs:string"/>
						<xs:element name="role" type="xs:string"/>
						</xs:sequence>
					</xs:complexType>
					</xs:element> <!--user-->
				</xs:sequence>
			</xs:complexType>
			</xs:element><!--users-->
			<xs:element name="Courses">
			<xs:complexType>
			<xs:sequence>
			<xs:element name="course" maxOccurs="unbounded">
			<xs:complexType>
				<xs:sequence>
				<xs:element name="cID" type="xs:integer"/>
				<xs:element name="cName" type="xs:string"/>
				<xs:element name="totalsessionNum" type="xs:integer"/>
				<xs:element name="sessions">
				<xs:complexType>
					<xs:sequence>
					<xs:element name="session" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						<xs:element name="date" type="xs:date"/>
						<xs:element name="sessionNum" type="xs:integer"/>
						<xs:element name="students" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
					<xs:element  name="student" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
						<xs:element name="stdId" type="xs:integer"/>
						<xs:element name="status" type="status"/>
						</xs:sequence>
					</xs:complexType>
					</xs:element> <!--student-->
					</xs:sequence>
				</xs:complexType>
				</xs:element> <!--students-->
				
						</xs:sequence>
					</xs:complexType>
					</xs:element> <!--session-->
					</xs:sequence>
				</xs:complexType>
				</xs:element><!--sessions-->
				<xs:element name="teacher">
				<xs:complexType>
					<xs:sequence>
					<xs:element name="teachId" type="xs:integer"/>
					</xs:sequence>
				</xs:complexType>
				</xs:element> <!--teacher-->
				</xs:sequence>
			</xs:complexType>
			</xs:element> <!--course-->
			</xs:sequence>
			</xs:complexType>
			</xs:element> <!--courses-->
		</xs:sequence>
		</xs:complexType>
	</xs:element><!--data-->
</xs:schema>

=== AyaSHEHAT/Attendance_Project/XML files/Data.xml
<?xml version="1.0" encoding="UTF-8"?>
<Data xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Users\Saber\Desktop\Attendance_Project\XML files\Data.xsd">
	<Users>
		<user>
			<id>800159561</id>
			<name>aya</name>
			<email>aya@yahoo.com</email>
			<address>mansoura</address>
			<userPass>dfxyd78798</userPass>
			<role>student</role>
		</user>
		<user>
			<id>800151254</id>
			<name>aya</name>
			<email>aya@yahoo.com</email>
			<address>mansoura</address>
			<userPass>asdf1234</userPass>
			<role>student</role>
		</user>
		<user>
			<id>800151654</id>
			<name>aya</name>
			<email>aya@yahoo.com</email>
			<address>mansoura</address>
			<userPass>Ahsh1234</userPass>
			<role>student</role>
		</user>
		<user>
			<id>800153698</id>
			<name>aya</name>
			<email>aya@yahoo.com</email>
			<address>mansoura</address>
			<userPass>asdf1234</userPass>
			<role>student</role>
		</user>
		<user>
			<id>8123</id>
			<name>Helmy</name>
			<email>helmy@yahoo.com</email>
			<address>mansoura</address>
			<userPass>asdf1234</userPass>
			<role>teacher</role>
		</user>
		<user>
			<id>8456</id>
			<name>Ayman</name>
			<email>ayman@yahoo.com</email>
			<address>mansoura</address>
			<userPass>asdf1234</userPass>
			<role>teacher</role>
		</user>
		<user>
			<id>8789</id>
			<name>Nasr</name>
			<email>nasr@yahoo.com</email>
			<address>mansoura</address>
			<userPass>asdf1234</userPass>
			<role>teacher</role>
		</user>
		<user>
			<id>801</id>
			<name>mohamed</name>
			<email>mohamed@yahoo.com</email>
			<address>mansoura</address>
			<userPass>admin1234</userPass>
			<role>admin</role>
		</user>
	</Users>
	<Courses>
		<course>
			<cID>100</cID>
			<cName>XML</cName>
			<totalsessionNum>6</totalsessionNum>
			<sessions>
				<session>
					<date>2021-01-01</date>
					<sessionNum>1</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>present</status>
						</student>
					</students>
				</session>
				<session>
					<date>2021-01-02</date>
					<sessionNum>2</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>absent</status>
						</student>
					</students>
				</session>
				<session>
					<date>2021-01-03</date>
					<sessionNum>4</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>present</status>
						</student>
					</students>
				</session>
				<session>
					<date>2021-01-04</date>
					<sessionNum>5</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>present</status>
						</student>
					</students>
				</session>
			</sessions>
			<teacher>
				<teachId>8123</teachId>
			</teacher>
		</course>
		<course>
			<cID>200</cID>
			<cName>C#</cName>
			<totalsessionNum>6</totalsessionNum>
			<sessions>
				<session>
					<date>2021-02-01</date>
					<sessionNum>1</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>present</status>
						</student>
					</students>
				</session>
				<session>
					<date>2021-02-02</date>
					<sessionNum>2</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>absent</status>
						</student>
					</students>
				</session>
				<session>
					<date>2021-02-03</date>
					<sessionNum>3</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>present</status>
						</student>
					</students>
				</session>
				<session>
					<date>2021-04-06</date>
					<sessionNum>5</sessionNum>
					<students>
						<student>
							<stdId>800159561</stdId>
							<status>present</status>
						</student>
						<student>
							<stdId>800151234</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800152315</stdId>
							<status>absent</status>
						</student>
						<student>
							<stdId>800151254</stdId>
							<status>present</status>
						</student>
					</students>
				</session>
			</sessions>
			<teacher>
				<teachId>8456</teachId>
			</teacher>
		</course>
	</Courses>
</Data>
